development:
  adapter: postgresql
  database: clientela_development
  pool: 5
test:
  adapter: postgresql
  database: clientela_test
  pool: 5
  min_messages: WARNING

production:
  adapter: postgresql
  database: clientela_production
  pool: 5